apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-hackathon
  namespace: default  # Change to your desired namespace
  labels:
    app: logger-hackathon
spec:
  replicas: 1  # Change the number of replicas as needed
  selector:
    matchLabels:
      app: logger-hackathon
  template:
    metadata:
      labels:
        app: logger-hackathon
    spec:
      containers:
        - name: logger-hackathon
          image: tjain598/logger-hackathon:latest
          env:
            - name: ALLOWED_HOSTS
              value: "172.17.0.3,localhost,127.0.0.1"  # Add any additional hosts as needed
